data_ingestion:
  download_dir: data # Dataset Download Path
  dataset_id: balraj98/deepglobe-road-extraction-dataset # Kaggle Dataset ID

data_preparation:
  data_dir: data # Dataset Directory
  metadata_csv: data/metadata.csv # Metadata CSV
  out_metadata_csv: data/metadataV2.csv # Output Metadata CSV after Splitting Training into Training, Testing and Validation Sets

training:
  metadata_csv: data/metadataV2.csv # Metadata CSV
  logs_dir: logs # Logs Directory

evaluation:
  models_dir: models # Model Directory
  metadata_csv: data/metadataV2.csv # Metadata CSV
  results_dir: results # Results Directory
  metrics_filepath: results/metrics.json # Metrics Filepath 