data_ingestion:
  download_dir: data # Dataset Download Path
  dataset_id: balraj98/deepglobe-road-extraction-dataset # Kaggle Dataset ID

data_preparation:
  data_dir: data
  metadata_path: data/metadata.csv # Original Metadata
  processed_metadata_path: data/processed_metadata.csv # Processed Metadata