random_state: 26

# Data Preparation
train_val_split: [0.7, 0.2, 0.1] # Train - Test - Val Split Ratio

# Data Loader
batch_size: 12
num_workers: 24
prefetch_factor: 12
resize_dimension: 512
apply_preprocessing: False

# Training
architecture: Unet # https://smp.readthedocs.io/en/latest/models.html
encoder: resnet101 # https://smp.readthedocs.io/en/latest/encoders.html
encoder_weights: imagenet
epochs: 25
lr: 0.00001
n_classes: 1
tune_lr: False
n_channels: 3
device: cuda # cuda, cpu, mps, auto
checkpoint_path: models/checkpoints/epoch=12-val_f1=0.57.ckpt # None if checkpoint not available
optimizer: adamax
loss: JaccardLoss # https://smp.readthedocs.io/en/latest/losses.html

# Evaluation
model_path: models/best.pt

# Available Metrics
# iou: IoU
# f1: Fscore
# f2: F2Score
# precision: Precision
# recall: Recall

# Available Losses
# DiceLoss
# FocalLoss
# TverskyLoss
# JaccardLoss
# LovaszLoss
# SoftBCEWithLogitsLoss ---- Not Working
# SoftCrossEntropyLoss
# MCCLoss

# Available Optimizers
# adam: Adam
# adamw: AdamW
# adagrad: Adagrad
# adadelta: Adadelta
# adamax: Adamax
# asgd: ASGD
# sgd: SGD
# rmsprop: RMSprop

# Available Models
# DeepLabV3Plus
# DeepLabV3
# Unet
# UNetPlusPlus
# Linknet
# PSPNet
# FPN
# MAnet
# PAN

# Available Encoders
# resnet18: ResNet18
# resnet34: ResNet34
# resnet50: ResNet50
# resnet101: ResNet101
# resnet152: ResNet152

# Available Device
# cpu: cpu
# cuda: cuda
# mps: mps
