random_state: 26

# Data Preparation
train_val_split: [0.7, 0.2, 0.1] # Train - Test - Val Split Ratio

# Data Loader
batch_size: 16
num_workers: 32
resize_dimension: 512
apply_preprocessing: False

# Training
architecture: DeepLabV3Plus # https://smp.readthedocs.io/en/latest/models.html
encoder: resnet50 # https://smp.readthedocs.io/en/latest/encoders.html
encoder_weights: imagenet
epochs: 25 # Must be greter than the epoch number in the checkpoint otherwise it will throw an error. If no checkpoint is available then it will start from scratch so adjust accordingly.
lr: 0.004
n_classes: 1
tune_lr: False
dev_run: False # Only for testing purposes - executes only 1 epoch without training - not compatible with checkpoint
n_channels: 3
device: auto # cuda, cpu, mps, auto
checkpoint_path: logs/DeepLabV3Plus_resnet50/checkpoints/epoch=22-val_f1=0.72.ckpt # None if checkpoint not available
optimizer: adamax
loss: JaccardLoss # https://smp.readthedocs.io/en/latest/losses.html

# Evaluation
model_path: logs/DeepLabV3Plus_resnet50/checkpoints/epoch=22-val_f1=0.72.ckpt
save_predictions: True # Plots predictions on a randomly chosen batch from test dataloader and saves them as PNG
f1_threshold: 0.7 # Save model as ONNX only if the evaluation test_f1 is greater than the f1_threshold
# Baseline F1 Score - if the evaluation test_f1 is less than the f1_threshold then the model is considered as underperforming, otherwise it is considered as overperforming and the model is considered as good. We will save the model only if the evaluation test_f1 is greater than the f1_threshold. Model will be saved as ONNX format. The saved model will be used in production.


# Available Losses
# DiceLoss
# FocalLoss
# TverskyLoss
# JaccardLoss
# LovaszLoss
# SoftBCEWithLogitsLoss ---- Not Working
# SoftCrossEntropyLoss
# MCCLoss

# Available Optimizers
# adam: Adam
# adamw: AdamW
# adagrad: Adagrad
# adadelta: Adadelta
# adamax: Adamax
# asgd: ASGD
# sgd: SGD
# rmsprop: RMSprop

# Available Models
# DeepLabV3Plus
# DeepLabV3
# Unet
# UNetPlusPlus
# Linknet
# PSPNet
# FPN
# MAnet
# PAN

# Available Encoders
# resnet18: ResNet18
# resnet34: ResNet34
# resnet50: ResNet50
# resnet101: ResNet101
# resnet152: ResNet152

# Available Device
# cpu: cpu
# cuda: cuda
# mps: mps
