random_state: 26

# Data Preparation
train_val_split: [0.7, 0.2, 0.1] # Train - Test - Val Split Ratio

# Data Loader
batch_size: 6
num_workers: 0
prefetch_factor: 6
resize_dimension: 512

# Training
architecture: PAN # https://smp.readthedocs.io/en/latest/models.html
encoder: resnet18 # https://smp.readthedocs.io/en/latest/encoders.html
encoder_weights: imagenet
epochs: 25
learning_rate: 0.0001
num_classes: 1
classes: [road]
num_channels: 3
device: auto
precision: 16
checkpoint_path: None
optimizer: Adam
loss: FocalLoss # https://smp.readthedocs.io/en/latest/losses.html

# Evaluation
model_path: models/best.pt
# metrics: [iou, f1, precision, recall]

# Available Metrics
# iou: IoU
# f1: Fscore
# precision: Precision
# recall: Recall

# Available Losses
# dice: DiceLoss
# cross_entropy: CrossEntropyLoss

# Available Optimizers
# adam: Adam
# sgd: SGD

# Available Models
# deeplabv3plus: DeepLabV3Plus
# deeplabv3: DeepLabV3
# unet: UNet
# unetplusplus: UNetPlusPlus
# linknet: LinkNet
# pspnet: PSPNet
# fpn: FPN
# manet: MAnet
# pan: PAN

# Available Encoders
# resnet18: ResNet18
# resnet34: ResNet34
# resnet50: ResNet50
# resnet101: ResNet101
# resnet152: ResNet152

# Available Device
# cpu: cpu
# cuda: cuda
