random_state: 26

# Data Preparation
train_val_split: [0.7, 0.2, 0.1] # Train - Test - Val Split Ratio

# Data Loader
batch_size: 6
num_workers: 0
prefetch_factor: 6
resize_dimension: 512

# Training
architecture: DeepLabV3Plus # https://smp.readthedocs.io/en/latest/models.html
encoder: resnet18 # https://smp.readthedocs.io/en/latest/encoders.html
encoder_weights: imagenet
epochs: 25
learning_rate: 0.0001
num_classes: 1
classes: [road]
num_channels: 3
device: auto
precision: 16
checkpoint_path: None
optimizer: Adam
metrics: [IoU, Fscore] # https://smp.readthedocs.io/en/latest/metrics.html
loss: DiceLoss # https://smp.readthedocs.io/en/latest/losses.html

# Evaluation
model_path: models/best.pt
# metrics: [iou, f1, precision, recall]

